### ISSUE TITLE
Custom variables with native dark/light mode support

### ISSUE THREAD

**Issue by codewithkyle** [codewithkyle/brixi#18]
Add a new `variables` object to the config allowing developers to define / control custom variables using Brixi.

### Input

```javascript
{
    variables: {
        dark: {
            "custom-variable": "rgba(255, 255, 255, 0.3)",
            "primary": "var(--blue-300)",
        },
        light: {
            "custom-variable": "rgba(0, 0, 0, 0.15)"
            "primary": "var(--blue-700)",
        },
        both: {
            "another-custom-variable": "rotate(30deg) translateY(96px)",
        }
    }
}
```

### Output

```css
:root{
    /* ...snip... */

    /* begin custom variables */
    --another-custom-variable: rotate(30deg) translateY(96px);
}
@media (prefers-color-scheme: dark) {
    :root {
       --custom-variable: rgba(0, 0, 0, 0.15);
       --primary: var(--blue-700);
    }
}
@media (prefers-color-scheme: dark) {
    :root {
        --custom-variable: rgba(255, 255, 255, 0.3);
        --primary: var(--blue-300);
    }
}
```

**Comment by codewithkyle** [comment]
```css
:root[theme="dim"]{
    --primary: var(--blue-300);
    --background: var(--neutral-700);
}

@media (prefers-color-scheme: dark) {
    :root {
        --primary: var(--blue-300);
        --background: var(--neutral-900);
    }
}

@media (prefers-color-scheme: light) {
    :root {
        --primary: var(--amber-700);
        --background: var(--neutral-100);
    }
}
```

**Comment by codewithkyle** [comment]
We should figure out how to allow developers to map a custom "dark" and "light" theme attribute value to the dark & light auto values.

**Comment by codewithkyle** [comment]
> We should figure out how to allow developers to map a custom "dark" and "light" theme attribute value to the dark & light auto values.

The dark and light themes should be available as direct themes and automatic themes.

```css
:root[theme="dim"]{
    --primary: var(--blue-300);
    --background: var(--neutral-700);
}

@media (prefers-color-scheme: dark) {
    :root[theme="auto"]{
        --primary: var(--blue-300);
        --background: var(--neutral-900);
    }
}

@media (prefers-color-scheme: light) {
    :root[theme="auto"]{
        --primary: var(--amber-700);
        --background: var(--neutral-100);
    }
}

:root[theme="dark"]{
    --primary: var(--blue-300);
    --background: var(--neutral-900);
}

:root[theme="light"]{
    --primary: var(--amber-700);
    --background: var(--neutral-100);
}
```
