### ISSUE TITLE
Expanding upon Light vs Dark modes

### ISSUE THREAD

**Issue by codewithkyle** [codewithkyle/brixi#27]
Currently I am experimenting with flipping the variables. For example `--grey-800` could becomes `--grey-200`

One of the issues I've seen is flipping from something like `bg-white` to a semi-transparent background. This is the same for border colors `border-grey-300` would need to become `border-grey-500` in dark mode.

I don't like the Tailwind solution (`dark:` and `light:` prefixes) because it will 3x our output file size. 

My current solution is to use AlpineJS: 
```
:class="window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'a' : 'b'"
```

This could also be solved by tracking a light/dark mode cookie for SSR projects but I think we lose the 'use system preference' functionality.

**Comment by codewithkyle** [comment]
I should clarify the maximum output of the `bg-{color}` and `font-{color}` would be 3x the current output.

If we go the prefix route we could add a new section to the config file that forces developers to explicitly enable the prefixes:

```javascript
prefixes: {
    dark: {
        features: ["fonts", "backgrounds"],
        rule: "prefers-color-scheme: dark" // media rule
    },
    sm: {
        features: ["containers", "display"],
        rule: "min-width: 411px" // media rule
    }
}
```

This could then generate something like:

```css
@media (prefers-color-scheme: dark) {
    .dark:bg-white {
        background-color: var(--white) !important;
    }
}
@media (min-width: 411px) {
    .sm:block{
        display: block;
    }
}
```
