### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by codewithkyle** [codewithkyle/brixi#29]
Something I find myself occasionally needing is an opacity class. I don't see why adding this would be an issue:

**Input**
```
opacity: [0.05, 0.1, 0.3, 0.6, 0.87]
```

**Output**
```css
.o-5{
    opacity: 0.05
}
```
