### ISSUE TITLE
Aspect Ratios

### ISSUE THREAD

**Issue by codewithkyle** [codewithkyle/brixi#6]
Generated class like `ar-16:9` with these presets:

```javascript
aspectRatios: ["16:9", "4:3", "1:1"]
```

It will generate the following code:

```scss
// 16:9 example
.ar-16\:9{
    &::before{
        content:"";
        width: 100%;
        display: block;
        padding-bottom: "56.25%";
    }
}
```
